kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: predictors-rolebinding
subjects:
- kind: ServiceAccount
  name: mlx-api
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: predictors-role
  apiGroup: rbac.authorization.k8s.io