# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
#
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1.30-upload-catalog-from-url
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "mlx-client"
VERSION = "0.1.30-upload-catalog-from-url"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]
    

setup(
    name=NAME,
    version=VERSION,
    description="MLX API Client",
    license="Apache 2.0",
    author_email="",
    url="https://github.com/machine-learning-exchange/mlx",
    keywords=["Swagger", "MLX API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Machine Learning Exchange API Client
    """
)
