# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1.27-pipeline-namespace
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.api_model_framework_runtimes import ApiModelFrameworkRuntimes  # noqa: F401,E501


class ApiModelFramework(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'version': 'str',
        'runtimes': 'ApiModelFrameworkRuntimes'
    }

    attribute_map = {
        'name': 'name',
        'version': 'version',
        'runtimes': 'runtimes'
    }

    def __init__(self, name=None, version=None, runtimes=None):  # noqa: E501
        """ApiModelFramework - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._version = None
        self._runtimes = None
        self.discriminator = None

        self.name = name
        if version is not None:
            self.version = version
        if runtimes is not None:
            self.runtimes = runtimes

    @property
    def name(self):
        """Gets the name of this ApiModelFramework.  # noqa: E501


        :return: The name of this ApiModelFramework.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiModelFramework.


        :param name: The name of this ApiModelFramework.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def version(self):
        """Gets the version of this ApiModelFramework.  # noqa: E501


        :return: The version of this ApiModelFramework.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ApiModelFramework.


        :param version: The version of this ApiModelFramework.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def runtimes(self):
        """Gets the runtimes of this ApiModelFramework.  # noqa: E501


        :return: The runtimes of this ApiModelFramework.  # noqa: E501
        :rtype: ApiModelFrameworkRuntimes
        """
        return self._runtimes

    @runtimes.setter
    def runtimes(self, runtimes):
        """Sets the runtimes of this ApiModelFramework.


        :param runtimes: The runtimes of this ApiModelFramework.  # noqa: E501
        :type: ApiModelFrameworkRuntimes
        """

        self._runtimes = runtimes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiModelFramework, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiModelFramework):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
