# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mlx-api.yaml
  - mlx-ui.yaml
images:
  - name: mlexchange/mlx-api
    newTag: v0.2.0
  - name: mlexchange/mlx-ui
    newTag: v0.2.0
