# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: mlx-api
  namespace: kubeflow
  labels:
    service: mlx-api
    environment: dev
spec:
  ports:
  - name: mlx-api
    port: 80
    targetPort: 8080
  selector:
    service: mlx-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlx-api
  namespace: kubeflow
  labels:
    service: mlx-api
    environment: dev
spec:
  selector:
    matchLabels:
       service: mlx-api
       environment: dev
  replicas: 1
  template:
    metadata:
      labels:
        service: mlx-api
        environment: dev
        version: v0.1.25-related-assets
    spec:
      serviceAccountName: mlx-api
      containers:
      - name: mlx-api-server
        image: mlexchange/mlx-api:nightly-main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /apis/v1alpha1/health_check?check_database=true&check_object_store=true
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
          periodSeconds: 60
          failureThreshold: 3
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mlx-api-access
subjects:
- kind: ServiceAccount
  name: mlx-api
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: mlx-api-access
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlx-api-access
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets", "events", "serviceaccounts", "configmaps",
    "persistentvolumeclaims", "limitranges"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["serving.kubeflow.org"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["serving.knative.dev"]
  resources: ["services", "revisions", "configurations"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["serving.kserve.io"]
  resources: ["predictors", "inferenceservices"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlx-api
  namespace: kubeflow
