# Copyright 2021 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: olm-admin
  namespace: olm
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: olm-admin-extend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: olm-admin
    namespace: olm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: olm-console
  namespace: olm
  labels:
    service: olm-console
spec:
  replicas: 1
  selector:
    matchLabels:
      service: olm-console
  template:
    metadata:
      name: olm-console
      labels:
        service: olm-console
    spec:
      serviceAccountName: olm-admin
      containers:
      - name: olm-console
        image: quay.io/openshift/origin-console:latest
        imagePullPolicy: Always
        env:
        - name: BRIDGE_USER_AUTH
          value: 'disabled'
        - name: BRIDGE_K8S_MODE
          value: 'in-cluster'
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: olm-console
  namespace: olm
  labels:
    service: olm-console
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  type: NodePort
  selector:
    service: olm-console
