# Copyright 2021 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.api_parameter import ApiParameter  # noqa: F401,E501
from swagger_server import util


class ApiPipelineTaskArguments(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, parameters: List[ApiParameter]=None):  # noqa: E501
        """ApiPipelineTaskArguments - a model defined in Swagger

        :param parameters: The parameters of this ApiPipelineTaskArguments.  # noqa: E501
        :type parameters: List[ApiParameter]
        """
        self.swagger_types = {
            'parameters': List[ApiParameter]
        }

        self.attribute_map = {
            'parameters': 'parameters'
        }

        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'ApiPipelineTaskArguments':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiPipelineTaskArguments of this ApiPipelineTaskArguments.  # noqa: E501
        :rtype: ApiPipelineTaskArguments
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parameters(self) -> List[ApiParameter]:
        """Gets the parameters of this ApiPipelineTaskArguments.


        :return: The parameters of this ApiPipelineTaskArguments.
        :rtype: List[ApiParameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: List[ApiParameter]):
        """Sets the parameters of this ApiPipelineTaskArguments.


        :param parameters: The parameters of this ApiPipelineTaskArguments.
        :type parameters: List[ApiParameter]
        """

        self._parameters = parameters
