# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util  # noqa: F401


class ApiGenerateCodeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, script: str = None):  # noqa: E501
        """ApiGenerateCodeResponse - a model defined in Swagger

        :param script: The script of this ApiGenerateCodeResponse.  # noqa: E501
        :type script: str
        """
        self.swagger_types = {"script": str}

        self.attribute_map = {"script": "script"}

        self._script = script

    @classmethod
    def from_dict(cls, dikt) -> "ApiGenerateCodeResponse":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiGenerateCodeResponse of this ApiGenerateCodeResponse.  # noqa: E501
        :rtype: ApiGenerateCodeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def script(self) -> str:
        """Gets the script of this ApiGenerateCodeResponse.

        The script source code to run the component in a pipeline  # noqa: E501

        :return: The script of this ApiGenerateCodeResponse.
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script: str):
        """Sets the script of this ApiGenerateCodeResponse.

        The script source code to run the component in a pipeline  # noqa: E501

        :param script: The script of this ApiGenerateCodeResponse.
        :type script: str
        """

        self._script = script
