# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.api_settings_section import ApiSettingsSection  # noqa: F401,E501
from swagger_server import util


class ApiSettings(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, sections: List[ApiSettingsSection]=None):  # noqa: E501
        """ApiSettings - a model defined in Swagger

        :param sections: The sections of this ApiSettings.  # noqa: E501
        :type sections: List[ApiSettingsSection]
        """
        self.swagger_types = {
            'sections': List[ApiSettingsSection]
        }

        self.attribute_map = {
            'sections': 'sections'
        }

        self._sections = sections

    @classmethod
    def from_dict(cls, dikt) -> 'ApiSettings':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiSettings of this ApiSettings.  # noqa: E501
        :rtype: ApiSettings
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sections(self) -> List[ApiSettingsSection]:
        """Gets the sections of this ApiSettings.

        List of configuration categories.  # noqa: E501

        :return: The sections of this ApiSettings.
        :rtype: List[ApiSettingsSection]
        """
        return self._sections

    @sections.setter
    def sections(self, sections: List[ApiSettingsSection]):
        """Sets the sections of this ApiSettings.

        List of configuration categories.  # noqa: E501

        :param sections: The sections of this ApiSettings.
        :type sections: List[ApiSettingsSection]
        """
        if sections is None:
            raise ValueError("Invalid value for `sections`, must not be `None`")  # noqa: E501

        self._sections = sections
