# Copyright 2021 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.api_pipeline_task import ApiPipelineTask  # noqa: F401,E501
from swagger_server import util


class ApiPipelineDAG(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tasks: List[ApiPipelineTask]=None):  # noqa: E501
        """ApiPipelineDAG - a model defined in Swagger

        :param tasks: The tasks of this ApiPipelineDAG.  # noqa: E501
        :type tasks: List[ApiPipelineTask]
        """
        self.swagger_types = {
            'tasks': List[ApiPipelineTask]
        }

        self.attribute_map = {
            'tasks': 'tasks'
        }

        self._tasks = tasks

    @classmethod
    def from_dict(cls, dikt) -> 'ApiPipelineDAG':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apiPipelineDAG of this ApiPipelineDAG.  # noqa: E501
        :rtype: ApiPipelineDAG
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tasks(self) -> List[ApiPipelineTask]:
        """Gets the tasks of this ApiPipelineDAG.

        List of pipeline tasks.  # noqa: E501

        :return: The tasks of this ApiPipelineDAG.
        :rtype: List[ApiPipelineTask]
        """
        return self._tasks

    @tasks.setter
    def tasks(self, tasks: List[ApiPipelineTask]):
        """Sets the tasks of this ApiPipelineDAG.

        List of pipeline tasks.  # noqa: E501

        :param tasks: The tasks of this ApiPipelineDAG.
        :type tasks: List[ApiPipelineTask]
        """

        self._tasks = tasks
