# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from swagger_client.models.api_model import ApiModel  # noqa: E501


class TestApiModel(unittest.TestCase):
    """ApiModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiModel(self):
        """Test ApiModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_model.ApiModel()  # noqa: E501


if __name__ == '__main__':
    unittest.main()
