# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1.30-upload-catalog-from-url
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from swagger_client.models.api_catalog_upload_response import ApiCatalogUploadResponse  # noqa: E501


class TestApiCatalogUploadResponse(unittest.TestCase):
    """ApiCatalogUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCatalogUploadResponse(self):
        """Test ApiCatalogUploadResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_catalog_upload_response.ApiCatalogUploadResponse()  # noqa: E501


if __name__ == '__main__':
    unittest.main()
