# Copyright 2021 IBM Corporation
# 
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
# 
#     http://www.apache.org/licenses/LICENSE-2.0 
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License. 
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.model_service_api import ModelServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelServiceApi(unittest.TestCase):
    """ModelServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.model_service_api.ModelServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_approve_models_for_publishing(self):
        """Test case for approve_models_for_publishing

        """
        pass

    def test_create_model(self):
        """Test case for create_model

        """
        pass

    def test_delete_model(self):
        """Test case for delete_model

        """
        pass

    def test_download_model_files(self):
        """Test case for download_model_files

        Returns the model artifacts compressed into a .tgz (.tar.gz) file.  # noqa: E501
        """
        pass

    def test_generate_model_code(self):
        """Test case for generate_model_code

        """
        pass

    def test_get_model(self):
        """Test case for get_model

        """
        pass

    def test_get_model_template(self):
        """Test case for get_model_template

        """
        pass

    def test_list_models(self):
        """Test case for list_models

        """
        pass

    def test_run_model(self):
        """Test case for run_model

        """
        pass

    def test_set_featured_models(self):
        """Test case for set_featured_models

        """
        pass

    def test_upload_model(self):
        """Test case for upload_model

        """
        pass

    def test_upload_model_file(self):
        """Test case for upload_model_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
