# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client  # noqa: F401
from swagger_client.models.any_value import AnyValue  # noqa: F401, E501
from swagger_client.rest import ApiException  # noqa: F401


class TestAnyValue(unittest.TestCase):
    """AnyValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyValue(self):
        """Test AnyValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_value.AnyValue()
        pass


if __name__ == "__main__":
    unittest.main()
