# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1.30-upload-catalog-from-url
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.catalog_service_api import CatalogServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogServiceApi(unittest.TestCase):
    """CatalogServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.catalog_service_api.CatalogServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_all_assets(self):
        """Test case for list_all_assets

        """
        pass

    def test_upload_multiple_assets(self):
        """Test case for upload_multiple_assets

        """
        pass


if __name__ == '__main__':
    unittest.main()
