# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1.27-pipeline-namespace
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_list_catalog_upload_errors import ApiListCatalogUploadErrors  # noqa: E501
from swagger_client.rest import ApiException


class TestApiListCatalogUploadErrors(unittest.TestCase):
    """ApiListCatalogUploadErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListCatalogUploadErrors(self):
        """Test ApiListCatalogUploadErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_list_catalog_upload_errors.ApiListCatalogUploadErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
