# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.component_service_api import ComponentServiceApi  # noqa: E501


class TestComponentServiceApi(unittest.TestCase):
    """ComponentServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.component_service_api.ComponentServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_approve_components_for_publishing(self):
        """Test case for approve_components_for_publishing

        """

    def test_create_component(self):
        """Test case for create_component

        """

    def test_delete_component(self):
        """Test case for delete_component

        """

    def test_download_component_files(self):
        """Test case for download_component_files

        Returns the component artifacts compressed into a .tgz (.tar.gz) file.  # noqa: E501
        """

    def test_generate_component_code(self):
        """Test case for generate_component_code

        """

    def test_get_component(self):
        """Test case for get_component

        """

    def test_get_component_template(self):
        """Test case for get_component_template

        """

    def test_list_components(self):
        """Test case for list_components

        """

    def test_run_component(self):
        """Test case for run_component

        """

    def test_set_featured_components(self):
        """Test case for set_featured_components

        """

    def test_upload_component(self):
        """Test case for upload_component

        """

    def test_upload_component_file(self):
        """Test case for upload_component_file

        """


if __name__ == '__main__':
    unittest.main()
