# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client  # noqa: F401
from swagger_client.models.api_list_components_response import (  # noqa: F401
    ApiListComponentsResponse,
)
from swagger_client.rest import ApiException  # noqa: F401


class TestApiListComponentsResponse(unittest.TestCase):
    """ApiListComponentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiListComponentsResponse(self):
        """Test ApiListComponentsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_list_components_response.ApiListComponentsResponse()
        pass


if __name__ == "__main__":
    unittest.main()
