# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from swagger_client.models.api_settings import ApiSettings  # noqa: E501


class TestApiSettings(unittest.TestCase):
    """ApiSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiSettings(self):
        """Test ApiSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_settings.ApiSettings()  # noqa: E501


if __name__ == '__main__':
    unittest.main()
