# Copyright 2021 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1.29-filter-categories
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_catalog_upload_item import ApiCatalogUploadItem  # noqa: E501
from swagger_client.rest import ApiException


class TestApiCatalogUploadItem(unittest.TestCase):
    """ApiCatalogUploadItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCatalogUploadItem(self):
        """Test ApiCatalogUploadItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_catalog_upload_item.ApiCatalogUploadItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
