# Copyright 2021 The MLX Contributors
#
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

"""
    MLX API

    MLX API Extension for Kubeflow Pipelines  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

from swagger_client.models.api_generate_model_code_response import ApiGenerateModelCodeResponse  # noqa: E501


class TestApiGenerateModelCodeResponse(unittest.TestCase):
    """ApiGenerateModelCodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiGenerateModelCodeResponse(self):
        """Test ApiGenerateModelCodeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_generate_model_code_response.ApiGenerateModelCodeResponse()  # noqa: E501


if __name__ == '__main__':
    unittest.main()
