name: Build and publish Python package

on:
  push:
    tags:
      - 'v*'                  # publish only on tag pushes like v1.2.3

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # necessary for setuptools_scm to see tags

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build & twine
        run: python -m pip install --upgrade pip build twine setuptools_scm

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel

      - name: Check artifacts
        run: ls -l dist

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine check dist/*
          python -m twine upload dist/* --non-interactive
